# Generated by Django 5.0.6 on 2024-05-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subdomain',
            field=models.CharField(default='www', max_length=50, unique=True),
        ),
    ]
