# Generated by Django 5.0.6 on 2024-05-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='anonymous', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
