# Generated by Django 5.0.6 on 2024-05-26 18:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_username'),
        ('session', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Session',
            new_name='StudentSession',
        ),
    ]
