# Generated by Django 5.0.6 on 2024-05-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_rename_student_session_studentsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSession',
        ),
    ]
