# Generated by Django 5.0.6 on 2024-05-27 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_user_username'),
        ('session', '0003_delete_studentsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_status', models.BooleanField(default=False)),
                ('gpa', models.DecimalField(decimal_places=2, default=None, max_digits=3)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentsession',
            constraint=models.UniqueConstraint(fields=('student', 'session', 'organization'), name='student_session_pk1'),
        ),
        migrations.AddConstraint(
            model_name='studentsession',
            constraint=models.UniqueConstraint(fields=('student', 'organization'), name='student_session_pk2'),
        ),
    ]
